[build-system]
requires = ["setuptools>=40.6.0", "wheel", "setuptools_scm>=8",]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
local_scheme = 'no-local-version'
version_scheme = 'only-version'
